### Topic 4 Numpy

Numpy is open source library for python

import numpy as np

numpy lebih cepat untuk proses data dan komputasi matematik


**1.2 Terminology**

array -> Vector -> Matrix

**1.3 Array**

np.array()

np.zeros()

np.ones()

np.empty()

np.arange()


In [3]:
import numpy as np
a = np.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(6)  #random dari state memory

array([1., 1., 1., 1., 1., 1.])

In [7]:
print(np.arange(4))
print(np.arange(0,10,2)) #start, stop, state

[0 1 2 3]
[0 2 4 6 8]


**Add, remove and sort**

np.delete()
np.sort()

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])

In [13]:
np.append(arr,[1,2]) #tidak disimpan di variable hanya operasi saja

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
print(arr)

[1 2 3 4 5 6 7 8]


In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

**Shape and Size**

In [92]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)
                        

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [93]:
array_example.ndim

3

In [94]:
array_example.size

24

In [95]:
array_example.shape

(3, 2, 4)

In [20]:
arr_one = np.array([1,2,3,4,5])

In [21]:
arr_one.ndim

1

In [23]:
arr_one.size

5

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

**Convert Array 1D to 2D**

In [39]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [41]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [42]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [43]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [45]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [46]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

**indexing and slicing**

In [49]:
data = np.array ([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:0])

[1 2 3]
1
2
[1 2]
[2 3]
[]


In [50]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
print(a[a<5])

[1 2 3 4]


In [54]:
five_up = (a>= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [55]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [56]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


**Creating Array from existing Data**

a. slicing indexing

b. np.vstack()

np.hstack()

np.haplit()

.view()

.copy()

In [59]:
arr =([1,2,3,4,5,6,7,8,9,10]) # ada yang kelewat

In [65]:
arr1 = arr[3:8]
arr1

[4, 5, 6, 7, 8]

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays:

a_1:

    array([[1, 1],
         [2, 2]])
and a_2:

    array([[3, 3],
         [4, 4]])

In [68]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [69]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [70]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [71]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [72]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [73]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [74]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [75]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Basic Array Operation**

data - ones

data + ones

data / ones

In [80]:
a = np.array([1,2,3,4])
a.sum()

10

In [81]:
b = np.array([[1,1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [82]:
b.sum(axis=0)

array([3, 3])

In [83]:
b.sum(axis=1)

array([2, 4])

In [84]:
data = np.array([1, 2])
data

array([1, 2])

In [86]:
ones = np.ones(2)
ones

array([1., 1.])

In [87]:
data + ones

array([2., 3.])

In [88]:
data * ones

array([1., 2.])

In [89]:
data - ones

array([0., 1.])

**Broadcasting** carry operation between arry and singel number

In [90]:
data * 2

array([2, 4])

In [91]:
ones * 2

array([2., 2.])

**More Array operation**  maximum, minimum, sum, mean, product, standard deviation, and more

In [96]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [97]:
A.sum()

4.8595784

In [98]:
A.min()

0.05093587

In [99]:
A.max()

0.82485143

In [101]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [102]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

**Martix Aritmetic**

In [104]:
data = np.array([[1,2],[3, 4]])
data

array([[1, 2],
       [3, 4]])

In [109]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [110]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [111]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.150398   0.00875528]
 [0.47758902 0.58861886]
 [0.34106897 0.04924991]]


**Dot Product**

In [117]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)


a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [118]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

**Matrix Indexing** for manipurating matrix

In [120]:
data = np.array([[1,2], [3, 4], [5, 6]])

print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


**Matrix Aggregation**

In [121]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [122]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [123]:
print(data.max(axis=1))
print(data.max(axis=0))

[2 4 6]
[5 6]


**Transposing and Reshaping Matrix**

In [124]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [125]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [126]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [127]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


**N-Dimestion Array**

In [131]:
ndar = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(ndar)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flatten N-Dimention Array**

In [133]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Working with Math Formula**

#Find regression

error = (1/n) *np.sum(np.square(observed - prediction))

**Notes on Numpy Vector**

In [137]:
a = np.random.rand(5)
print(a)

[0.6598089  0.16337828 0.42742994 0.92538583 0.54792181]


In [138]:
a.shape # Rank 1 Array

(5,)

In [139]:
print(a.T)

[0.6598089  0.16337828 0.42742994 0.92538583 0.54792181]


In [140]:
print(np.dot(a, a.T))

1.8012938376428194


In [144]:
a = np.random.rand(5,1) # row Vector
print(a)

[[0.94927947]
 [0.18911239]
 [0.20090015]
 [0.3663034 ]
 [0.96031704]]


In [145]:
print(a.T)

[[0.94927947 0.18911239 0.20090015 0.3663034  0.96031704]]


In [147]:
print(np.dot(a, a.T))

[[0.90113152 0.17952051 0.19071039 0.3477243  0.91160925]
 [0.17952051 0.0357635  0.03799271 0.06927251 0.18160785]
 [0.19071039 0.03799271 0.04036087 0.07359041 0.19292784]
 [0.3477243  0.06927251 0.07359041 0.13417818 0.35176739]
 [0.91160925 0.18160785 0.19292784 0.35176739 0.92220881]]


In [151]:
a = np.random.rand(1,5) #row Vector
print(a)

[[0.2981943  0.79945669 0.45226467 0.53120754 0.66861049]]


**Additional Example**

In [153]:
a = np.array([[3,4,2]])
a

array([[3, 4, 2]])

In [155]:
b = np.array([[13,9,7,15],[8,7,4,6],[6,4,0,3]])
b

array([[13,  9,  7, 15],
       [ 8,  7,  4,  6],
       [ 6,  4,  0,  3]])

In [156]:
np.dot(a,b)

array([[83, 63, 37, 75]])

In [157]:
a = np.array([[1,2,3,4,5,6,7]])
print(a)

[[1 2 3 4 5 6 7]]


In [158]:
np.save('H8',a)

In [160]:
b = np.load('H8.npy')

In [161]:
print(b)

[[1 2 3 4 5 6 7]]


In [165]:
arr2D = np.array([[11, 12, 13, 22], [21, 7, 23, 14], [31, 10, 33, 7]])
print(arr2D)

[[11 12 13 22]
 [21  7 23 14]
 [31 10 33  7]]


In [168]:
np.savetxt('h8.csv', arr2D)

In [169]:
np.loadtxt('h8.csv')

array([[11., 12., 13., 22.],
       [21.,  7., 23., 14.],
       [31., 10., 33.,  7.]])